# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-23 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('mobile', models.IntegerField()),
                ('subject', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Regis_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
