# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-03 04:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateField(default=datetime.date(2018, 5, 3)),
        ),
    ]
