# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-23 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_account',
            fields=[
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='homepage.Regis_db')),
                ('fullname', models.CharField(max_length=40)),
                ('department', models.CharField(max_length=40)),
                ('designation', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=128)),
                ('mobile', models.IntegerField()),
                ('bday', models.DateField()),
                ('add1', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('filename', models.ImageField(blank=True, null=True, upload_to='')),
                ('account', models.IntegerField()),
                ('bank', models.CharField(max_length=40)),
                ('pfaccount', models.IntegerField()),
                ('joining_date', models.DateField()),
            ],
        ),
    ]
